In [67]:
import pandas as pd
from sklearn.model_selection import train_test_split
import sentencepiece as spm
import torch

PATH = 'C:\Emotion Classification\data\\full_dataset\goemotions_1.csv'
TOKENIZER = 'C:\Emotion Classification\\traning\\vocab\\tokenizer.model'

<>:6: SyntaxWarning: invalid escape sequence '\E'
<>:7: SyntaxWarning: invalid escape sequence '\E'
<>:6: SyntaxWarning: invalid escape sequence '\E'
<>:7: SyntaxWarning: invalid escape sequence '\E'
C:\Users\illya\AppData\Local\Temp\ipykernel_23396\3030111412.py:6: SyntaxWarning: invalid escape sequence '\E'
  PATH = 'C:\Emotion Classification\data\\full_dataset\goemotions_1.csv'
C:\Users\illya\AppData\Local\Temp\ipykernel_23396\3030111412.py:7: SyntaxWarning: invalid escape sequence '\E'
  TOKENIZER = 'C:\Emotion Classification\\traning\\vocab\\tokenizer.model'

In [68]:
sp = spm.SentencePieceProcessor()
sp.load(TOKENIZER)

data = pd.read_csv(PATH, sep=',')
data.sample(5)

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
45724,"I can see the rippled sandy bottom, the shark ...",eergtud,fliminglaps,thalassophobia,t3_aiuszi,t3_aiuszi,1.548248e+09,61,False,0,...,0,0,0,0,0,0,0,0,0,0
34984,I didn't know that having the occupation of a ...,ed4v2zk,CarsGotBars,islam,t3_abu7yq,t1_ed4mqxd,1.546498e+09,50,False,0,...,0,0,0,0,1,0,0,0,0,0
68575,I thought he already left the country for an o...,ef2doz4,InterracialWombat,The_Mueller,t3_ak1lsp,t1_ef1ryk0,1.548557e+09,6,False,0,...,0,0,0,0,0,0,0,0,0,1
22304,You can wait ten years to start working on you...,ef3z3jw,Ahren_with_an_h,socialanxiety,t3_akd5rt,t3_akd5rt,1.548608e+09,8,False,0,...,0,0,0,0,0,0,0,0,0,1
16931,YOU WOULD THINK MISSISSIPPI STATE HAD GROWN ME...,ed5qym8,Skippy_Johnson,CFB,t3_ac706z,t3_ac706z,1.546534e+09,81,False,0,...,0,0,0,0,0,0,0,0,0,1

In [69]:
data.columns

Index(['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id', 'example_very_unclear', 'admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [70]:
data = data.drop(columns=['id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id'], axis=1)
data.columns, data.sample(5)

(Index(['text', 'example_very_unclear', 'admiration', 'amusement', 'anger',
        'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire',
        'disappointment', 'disapproval', 'disgust', 'embarrassment',
        'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love',
        'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse',
        'sadness', 'surprise', 'neutral'],
       dtype='object'),
                                                     text  \
 31783  The last two years of heart-breaking Saints pl...
 10855  My faith in humanity is restored. Your good de...
 11229  Went on a date with a guy getting paid to do a...
 45294                                 You president now?
 16755                                   What happened ?!

        example_very_unclear  admiration  amusement  anger  annoyance  \
 31783                 False           0          0      0          0
 10855                 False           0          0      0          0
 11229                 False           0          0      0          0
 45294                 False           0          0      0          0
 16755                 False           0          0      0          0

        approval  caring  confusion  curiosity  ...  love  nervousness  \
 31783         0       0          0          0  ...     0            0
 10855         0       0          0          0  ...     0            0
 11229         0       0          0          0  ...     0            0
 45294         0       0          0          1  ...     0            0
 16755         0       0          0          1  ...     0            0

        optimism  pride  realization  relief  remorse  sadness  surprise  \
 31783         0      0            0       0        0        1         0
 10855         0      1            0       1        0        0         0
 11229         0      0            0       0        0        0         0
 45294         0      0            0       0        0        0         0
 16755         0      0            0       0        0        0         0

        neutral
 31783        0
 10855        0
 11229        1
 45294        0
 16755        0

 [5 rows x 30 columns])

In [71]:
data.dtypes

text                    object
example_very_unclear      bool
admiration               int64
amusement                int64
anger                    int64
annoyance                int64
approval                 int64
caring                   int64
confusion                int64
curiosity                int64
desire                   int64
disappointment           int64
disapproval              int64
disgust                  int64
embarrassment            int64
excitement               int64
fear                     int64
gratitude                int64
grief                    int64
joy                      int64
love                     int64
nervousness              int64
optimism                 int64
pride                    int64
realization              int64
relief                   int64
remorse                  int64
sadness                  int64
surprise                 int64
neutral                  int64
dtype: object

In [72]:
data.text[1]

' >sexuality shouldnâ€™t be a grouping category It makes you different from othet ppl so imo it fits the definition of "grouping" '

In [73]:
def transform_data(data):
    data["text"] = data["text"].apply(lambda x: sp.encode(x, out_type=int))
    data["text"] = data["text"].apply(lambda x: torch.tensor(x, dtype=torch.int64))
    # data["text"] = torch.tensor(data["text"], dtype=torch.int64)
    return data

In [74]:
transform_data(data)

,text,example_very_unclear,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,"[tensor(41470), tensor(41586), tensor(15702), ...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,"[tensor(415), tensor(17557), tensor(1822), ten...",True,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"[tensor(41470), tensor(0), tensor(11), tensor(...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,"[tensor(41470), tensor(41585), tensor(28), ten...",False,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[tensor(60), tensor(0), tensor(41585), tensor(...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,"[tensor(41470), tensor(0), tensor(41472), tens...",False,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69996,"[tensor(41470), tensor(41586), tensor(8333), t...",False,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69997,"[tensor(41470), tensor(0), tensor(41499), tens...",False,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
69998,"[tensor(41470), tensor(0), tensor(41473), tens...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
69999,"[tensor(41470), tensor(41586), tensor(8333), t...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [75]:
data.example_very_unclear = data.example_very_unclear.astype(int)

In [76]:
data

,text,example_very_unclear,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,"[tensor(41470), tensor(41586), tensor(15702), ...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,"[tensor(415), tensor(17557), tensor(1822), ten...",1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"[tensor(41470), tensor(0), tensor(11), tensor(...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,"[tensor(41470), tensor(41585), tensor(28), ten...",0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[tensor(60), tensor(0), tensor(41585), tensor(...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,"[tensor(41470), tensor(0), tensor(41472), tens...",0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69996,"[tensor(41470), tensor(41586), tensor(8333), t...",0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69997,"[tensor(41470), tensor(0), tensor(41499), tens...",0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
69998,"[tensor(41470), tensor(0), tensor(41473), tens...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
69999,"[tensor(41470), tensor(41586), tensor(8333), t...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
data.to_csv('C:\Emotion Classification\\traning\in_model_data\\data.csv', index=False)

In [83]:
data.dtypes

text                    object
example_very_unclear     int64
admiration               int64
amusement                int64
anger                    int64
annoyance                int64
approval                 int64
caring                   int64
confusion                int64
curiosity                int64
desire                   int64
disappointment           int64
disapproval              int64
disgust                  int64
embarrassment            int64
excitement               int64
fear                     int64
gratitude                int64
grief                    int64
joy                      int64
love                     int64
nervousness              int64
optimism                 int64
pride                    int64
realization              int64
relief                   int64
remorse                  int64
sadness                  int64
surprise                 int64
neutral                  int64
dtype: object